### ISSUE TITLE
Explore How to Add New Homes from Public Survey Submissions

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/urban-league-heat-pump-accelerator#190]
As a user I might visit bostonhpa.org and want to submit a survey. As a part of this submission I will include my address. We need to figure out whether:

* We can simply import the entire Boston address DB and let the user select through filtering (somehow?) but this could be very messy in relation to the assignment groups because now we have a large chunk of un assigned homes and this will make using that interface a pain in the ass.
* We can potentially use Pelias or another geocoding API to validate a user String of their address and include it in the Survey submission. Then maybe the admin or Surveyor will go through and pick the appropriate Home based on this validated String and create the association. If we go this route we need to setup the validator, and also the front-end needs an interface for doing this.
* Third option is we YOLO let user enter a non-validated address and pray we can match it to the address list. I think this still will need a front end interface for connecting the home to the SurveyResponse after its submitted by a Surveyor.

**Comment by mikelynch** [comment]
Agreed re: option 1. Would also vote to avoid this.

For 2 vs 3, I guess the key question is whether we think we can synchronously do this kind of address validation (i.e. the same way when you're buying something online it canonicalizes your address and shows you the corrected one). If this is possible, then we can integrate this into the workflow (so that we only ever store the canonicalized version). If not, then presumably our only option would be to store the entered address, then periodically (e.g. batched up in a nightly job), we would canonicalize all the newly entered addresses, and tie them to the proper home record if they already exist (and if we're unable to work out what it was, then discard/flag up these records to admins?)

Obviously option 2 can be done – but possibly is more expensive? Either way we need the functionality to do the address canonicalization, so otherwise option 2 is probably slightly simpler – as it avoids the need to reconcile/merge records after the fact.
