### ISSUE TITLE
Admin: Homes: Clicking on a Home, show actual data. Hook it up to data

### ISSUE THREAD

**Issue by Rando-cal** [codeforboston/urban-league-heat-pump-accelerator#302]
Should it be editable. Need to ask Chris or Backend team

**Comment by LWest001** [comment]
In the Frontend_main build, I set up clicking on a Home to show data. I will leave this issue open until we get clarification about editability.

**Comment by LWest001** [comment]
@Rando-cal Is this issue to hook up to the real API, as in _not_ the jsonserver?

**Comment by LWest001** [comment]
I was able to hook this up to the jsonserver (`Frontend_main` branch), but there is a bit of an issue. `assignments.js` has two `assignment` objects, each of which has an array `homes` of objects. Those 'homes' have a bit of a different shape than the 'homes' objects inside of `homes.js`. There is nothing linking the 'homes' objects between these two json files. Currently, you click a home and it will always take you to the same object: the 'home' with an `id` of `1` inside `homes.js`. For whatever reason, all 'homes' inside `assignments.js` have this `id`.

The current shape of a 'home' inside of an 'assignment' in `assignments.json` is like this:
```
homes: [
      {
        id: 1,
        visit_order: 0,
        street_number: "38",
        street_name: "COLUMBIA RD",
        city: "DORCHESTER",
        zip_code: 2121,
        latitude: "42.30389054069225",
        longitude: "-71.08333573846997",
        completed: true,
      },
      //...rest of array
    ]
```

I'm thinking a better shape for the 'homes' inside of `assignments` would be as follows:
```
homes: [
  {
    id: 0, // The primary key of this array
    home_id: 3 // A foreign key that references a 'home' inside of homes.js
    visit_order: 1,
    latitude: "42.30396140002191", // This should probably be relocated to the referenced 'home' object inside of homes.js
    longitude: "-71.08175456568082", // This should probably also be relocated to the referenced object
    completed: false,
  }
  //...rest of array
]
```

That way, a 'home' inside of an 'assignment' just references a 'home' object rather than actually storing all the properties itself.

**Comment by LWest001** [comment]
I'm not sure if homes inside of `homes.js` have a surveyor attached. There is only an `assignment_id`, not a `surveyor_id`. I'll need this to supply to the Surveyor column on the Homes table.

**Comment by LWest001** [comment]
There is also not a property for completion in a home object, but there is a Completed column in the homes table.

**Comment by LWest001** [comment]
You can find progress on this issue in branch `leo-westebbe/issue-302-display-homes-data`.

**Comment by mattdelsordo** [comment]
You might have to pull in the assignment data to get the surveyor ID based on that. Alternatively you can just leave that out of the table and have the assignment ID column link to the assignments page. Feel free to change the table structure to match the data better.

**Comment by mattdelsordo** [comment]
We might want to ask back end to expose `completed` for the homes given that the alternative is a lot of searching on our end. I think it would make sense to store whether a home has been surveyed successfully on the data side as well.

**Comment by LWest001** [comment]
> You might have to pull in the assignment data to get the surveyor ID based on that. Alternatively you can just leave that out of the table and have the assignment ID column link to the assignments page. Feel free to change the table structure to match the data better.

@mattdelsordo So I implemented this using assignment id and an Assignment column. Clicking the cell takes you to the admin view assignment page. I wrapped the contents of an Assignment cell with a `<ToolTip/>` component that indicates that you will navigate to the associated `/assignment` page instead of the `/homeprofile` page because it breaks with the behavior of the rest of the row.
