### ISSUE TITLE
Admin view: Surveys table should display a list of survey visits

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#371]

**Comment by Rando-cal** [comment]
No data in Backend, maybe not why its showing ?????

**Comment by LWest001** [comment]
> No data in Backend, maybe not why its showing ?????

Right, like going to `/survey_visits.json` while the server is running serves an empty array.
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/189ee987-08a0-46a2-be70-ce279f8dac97)

@mikelynch is `/survey_visits` the right endpoint to hit for a list of all survey visits?

**Comment by mikelynch** [comment]
Yes, should be, but we don't seed any in the database so you'll need to create some first.

**Comment by thiagobardini** [comment]
@mikelynch Hi, I have a question. Why do we need a separate surves page? Can't we have the survey nested within the admin > home page instead?

**Comment by mikelynch** [comment]
Who's that question aimed at @thiagobardini ?

**Comment by thiagobardini** [comment]
It's a frontend question, but feel free to provide suggestions. I'm not sure why we need to display a table with all the survey visits. Do you think it is necessary for this MVP? @mikelynch

**Comment by thiagobardini** [comment]
Regarding the survey visit,
When you finish a survey and answer all the questions, I believe the survey visit is complete, right? @mikelynch

**Comment by mikelynch** [comment]
>Regarding the survey visit,
>When you finish a survey and answer all the questions, I believe the survey visit is complete, right? @mikelynch

Minor detail: it's not the `survey_visit` which is marked as complete, but the associated `survey_response`.

This is actually its own attribute, which is manually set. I'm not sure what the best UI is for this. If the surveyor (or anonymous user doing this online) doesn't want to answer a question, we still want to be able to indicate that the survey response is complete. Maybe if all questions are answered, we should auto-set complete to be true, but still give the user the option to mark as complete otherwise?

**Comment by mikelynch** [comment]
@mzagaja , any concerns with us manually extracting the survey responses for the data team, rather than having the front-end team code something up here? This probably shouldn't be a regular surveyor page anyway (more of an admin view) so while we may want to do this more than once, it's not going to have a lot of users.

**Comment by thiagobardini** [comment]
> >Regarding the survey visit,
> 
> >When you finish a survey and answer all the questions, I believe the survey visit is complete, right? @mikelynch
> 
> 
> 
> Minor detail: it's not the `survey_visit` which is marked as complete, but the associated `survey_response`.
> 
> 
> 
> This is actually its own attribute, which is manually set. I'm not sure what the best UI is for this. If the surveyor (or anonymous user doing this online) doesn't want to answer a question, we still want to be able to indicate that the survey response is complete. Maybe if all questions are answered, we should auto-set complete to be true, but still give the user the option to mark as complete otherwise?

Hi. To answer this question, we need to consider how the assignment page will work. The admin will create an assignment ID with a maximum of two surveyors and assign them a set of unsigned homes/surveys to visit in person. If the home user accesses their survey online and answers all the questions, you can mark it as complete and remove it from the surveyor assignment ID list. Please let me know your thoughts on this.

**Comment by mikelynch** [comment]
I assumed that the surveyors would have an assignment view – maybe some sort of map showing the homes on the map, and a table showing the details. I don't think we'd envisaged automatically removing a home from an assignment just because a survey was submitted publicly, but we could show that, something like:
<img width="596" alt="image" src="https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/2493182/6b4e60a2-806a-4423-947d-6a6fab288c5e">

**Comment by thiagobardini** [comment]
> I assumed that the surveyors would have an assignment view – maybe some sort of map showing the homes on the map, and a table showing the details. I don't think we'd envisaged automatically removing a home from an assignment just because a survey was submitted publicly, but we could show that, something like:
> 
> <img width="596" alt="image" src="https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/2493182/6b4e60a2-806a-4423-947d-6a6fab288c5e">
> 
> 

 Yes, I agree that we don't need to remove it. Here, we are discussing the ADMIN VIEW, where it will appear as "completed" in the assignment ID created for the surveyors assigned to it if the home user completes the survey online when it's already assigned to the surveyors. When it comes to the surveyor dashboard, it will also be displayed as "complete". It is possible to create a filter on the surveyor dashboard to show all the homes/surveys completed by each surveyor (VIEW ONLY).

Let me know what do you think about it.

**Comment by thiagobardini** [comment]
The Admin > Home view can be the place where we will have all the data. We can incorporate a table with filters and sorting options to find homes with incomplete or complete surveys and surveyors.

**Comment by LWest001** [comment]
I am closing this issue as it has been replaced by issue #416.
