### ISSUE TITLE
Login Remember me box: Get it working

### ISSUE THREAD

**Issue by Rando-cal** [codeforboston/urban-league-heat-pump-accelerator#421]

**Comment by mattdelsordo** [comment]
This is currently commented out. The way I think we want this to work is that it should only store the JWT in localstorage if the Remember button is checked (its currently doing this 100% of the time). See the extraReducers in loginSlice.js

**Comment by EfrainAD** [comment]
If the user refreshes the page, is the desired outcome that they are logged out?

**Comment by mattdelsordo** [comment]
On one hand I feel like no, but then we would need to store the JWT which defeats the purpose. The correct way to handle this would probably be to have the button control the expiry time of the token somehow, but short of that I think logging users out on refresh is fine.

**Comment by EfrainAD** [comment]
That is backend that would control this, since they choose when the token expires. From searching around, you can set it up with a refresh token for the 'remember me' that is used to re-login the user with a new session token. Though I am thinking they can just set the API to except a rememer me arg, then choose the expired time on that. 

Since the requirment is meet, I'll send the pull request for it.

**Comment by mattdelsordo** [comment]
Resolved by #436
