### ISSUE TITLE
Admin + Surveyor page to view completed surveys

### ISSUE THREAD

**Issue by mattdelsordo** [codeforboston/urban-league-heat-pump-accelerator#471]
In general, we don't have a component for viewing completed surveys. Probably makes sense to reuse the existing survey component, but make it read only.

Admin page:
- link in individual assignment page is broken
- should also be linked from home table but that is also missing

Surveyor page:
- we need some way to view complete surveys IN ADDITION to filling out new ones

**Comment by EfrainAD** [comment]
The surveyor needs a way to view complete surveys. 
How do you want this done? Surveyor can see if it's completed or not, but not see the answer as it is. 
1. Since we want them to be able to create multiple survey per house, how do you want to handle it when they click on it. I guessing two options. 1. If they want to see an old survey (and pick one if their is more then one), or 2. complete a new survey as it set now.
3. Do we want surveyors to be able to edit it?

"IN ADDITION to filling out new ones"
I don't know what this means, I misread and added a way to filter out completed homes. Maybe that's what you meant?

**Comment by mattdelsordo** [comment]
Re: how this should be done, we don't have any UX for this, so it's up to you how you want to design it. We definitely need some sort of a way to select from a list if there are multiple completed surveys.

As for the surveyor requirements, currently surveyors can fill out surveys for a home, but they can't view surveys that they've already submitted. I think we've decided in the past that surveyors should not be editing surveys and should just submit another one if it comes to it. Filtering out completed homes was not part of this but I see how that could be useful so you can probably hang on to that.

**Comment by mattdelsordo** [comment]
I'm going to re-open this to add the `SurveyLink` component + read-only survey page to the surveyor view.

**Comment by Rando-cal** [comment]
Andrewy-gh will take
